config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'my-received-bookings', to: 'pages#my_received_bookings'
  root to: 'boats#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :boats, only: [:show, :new, :create, :index, :destroy] do
    resources :bookings, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boat.rb
class Boat < ApplicationRecord
  belongs_to :owner, class_name: "User"
  has_many :bookings
  mount_uploader :photo, PhotoUploader
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :boat
  belongs_to :consumer, class_name: "User"

  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :boats, foreign_key: :owner_id
  has_many :bookings, foreign_key: :consumer_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [:home, :index, :show]
  before_action :set_user_boats
  before_action :set_user_bookings

  def set_user_bookings
    if current_user
      @my_bookings = current_user.bookings
    else
      @my_bookings = []
    end
  end

  def set_user_boats
    if current_user
      @my_boats = current_user.boats
    else
      @my_boats = []
    end
  end
    
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController

  def index
    @boats = Boat.all
    @owners = User.all
  end

  def show
    @boat = Boat.find(params[:id])
    @myboatbookings = Booking.where("consumer_id = ? AND boat_id = ?", current_user, @boat)
    @booking = Booking.new
  end

  def new
    @boat = Boat.new
  end

  def create
    @boat = Boat.new(boat_params)
    @boat.owner = current_user
    @boat.save
    if @boat.save
      redirect_to boat_path(@boat)
    else
      render :new
    end
  end

  def destroy
    @boat = Boat.find(params[:id])
    @boat.destroy
    redirect_to boats_path
  end

  private

  def boat_params
    params.require(:boat).permit(:owner_id, :day_price, :boat_name, :photo,
                                 :nbr_beds, :description)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @booking = Booking.new(booking_params)
    @booking.boat = Boat.find(params[:boat_id])
    @booking.consumer = current_user
    if @booking.save
      redirect_to boat_path(@booking.boat)
    else
      render "boats/show"
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:consumer_id, :boat_id, :start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def my_received_bookings
    @received_bookings = []
    if current_user
      current_user.boats.each do |boat|
        @received_bookings << boat.bookings
      end
    else
      @received_bookings = []
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boats/index.html.erb
<h1>Boats for rent in your region</h1>
<div class="div-scroller d-flex flex-wrap">
  <%@boats.each do |boat|%>
  <div class="card boat-card w-300">
    <p><%= link_to (cl_image_tag boat.photo, width: 300, height: 200, crop: :fill), boat_path(boat) %></p>
    <div class="card-details d-flex justify-content-between mr-2 ml-3">
      <div class="card-name">
        <%= boat.boat_name %>
      </div>
      <div class="card-avatar">
        <%= image_tag boat.owner.user_pic_url, class: "avatar card-avatar"%><br>
        <div class="card-info">
          <%= boat.nbr_beds %> <i class="fas fa-bed"></i><br>
          <%= boat.day_price %> €
        </div>
      </div>
    </div>
  </div>

  <% end %>
</div>

app/views/boats/new.html.erb
<div class="card rent_out">

<h1>Rent out your boat</h1>
<h6>Please take your time to describe your vessel. Have a think about what type of person will be reading this description. Will they understand your wording? Maybe you should try showing it to someone else and get their feedback.</h6>
<br>

<%= simple_form_for @boat, html: {class: "eau-form"} do |f|  %>
<div class="d-flex">
  <div class="row">
  <div class="col">
    <%= f.input :boat_name, :label => "The Name of the Boat", :placeholder => "MS Sister Mary Frances III", class: "form-input" %>
  </div>
  <div class="col">
    <%= f.input :day_price, :label => "Price per day (in euros, €)", :placeholder => "€ 200", class: "form-input" %>
  </div>
  <div class="col">
    <%= f.input :nbr_beds, :label => "Number of bunks", :placeholder => "65", class: "form-input" %>
  </div>
</div>
</div>
<%= f.input :description, :placeholder => "This fabulous steam machine was first launched in the Sussex harbor back in 1899. I has a crew of 16 people including 2 chefs. Top speed: 2.8 knots." %>

<div class="d-flex save_part">
  <div>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
  </div>
  <div id="save_end">
    <%= f.submit "Add new boat", class: "btn btn-primary btn btn-eau" %>
  </div>
</div>
<% end %>
</div>
</div>

app/views/boats/show.html.erb
<div class="card">
  <div class="show-boat-card d-flex justify-content-between">
    <div class="show-left">
      <%= cl_image_tag @boat.photo, width: 600, height: 350, crop: :fill %>
    </div>
    <% if !current_user || current_user.id != @boat.owner_id %>
    <div class="show-right ml-3 mr-3">
      <div class="d-flex justify-content-between">
        <div>
          <h1 class="boat-name"><%= @boat.boat_name %></h1>
        </div>
        <div>
          <p><%= image_tag @boat.owner.user_pic_url, class: "card-avatar", id: "avatar-large" %></p>
        </div>
      </div>
      <p><%= @boat.description %></p>
      <p>Number of bunks: <%= @boat.nbr_beds %> &nbsp <i class="fas fa-bed"></i></p>
      <p>Day price: <%= @boat.day_price %>€</p>
      <p>Owner email: <%= @boat.owner.email %></p>

      <%= simple_form_for [@boat, @booking] do |f| %>
      <div class="form-wrapper">
        <%= f.input :start_date, as: :string, required: false, input_html: {id: "range_start"} %>
        <%= f.input :end_date, as: :string, required: false, input_html: {id: "range_end"}  %>
        <%= f.submit "Add new booking", class: "btn booking-button btn-eau" %>
      </div>
      <% end %>

    </div>

    <% elsif current_user.id == @boat.owner_id %>
    <div class="show-right ml-3 mr-3">
      <div class="d-flex justify-content-between">
        <div>
          <h1 class="boat-name"><%= @boat.boat_name %></h1>
        </div>
        <div>
          <p><%= image_tag @boat.owner.user_pic_url, class: "card-avatar", id: "avatar-large" %></p>
        </div>
      </div>
      <p><%= @boat.description %></p>
      <p>Number of bunks: <%= @boat.nbr_beds %> &nbsp <i class="fas fa-bed"></i></p>
      <p>Day price: <%= @boat.day_price %>€</p>
      <p>Owner email: <%= @boat.owner.email %></p>
      <p><strong>This boat belongs to you!</strong></p>
      <%= link_to "Sink the boat", boat_path(@boat), method: :delete, class: "btn btn-danger" %>
    </div>
    <% end %>
  </div>
</div>
<% if !current_user || current_user.id != @boat.owner_id %>

<% unless @myboatbookings.empty? %>
<div class="card booking-card">
  <div class="d-flex">
    <div class="show-right ml-3 mr-3">
      <h3>My bookings:</h3>
      <ul>
        <% @myboatbookings.each do |booking| %>
        <li><%= booking.start_date %> -- <%= booking.end_date %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Eau-BnB</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= favicon_link_tag asset_path('favicon-32x32.png') %>
    <link href="https://fonts.googleapis.com/css?family=Cinzel|Montserrat" rel="stylesheet">
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
      <div id="mybanner">
        <%= render 'shared/banner' %>
      </div>
    </div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/my_received_bookings.html.erb
<h1>Bookings on my boats</h1>

<div class="d-flex flex-column">
  <% @received_bookings.each do |booking| %>
    <% booking.each do |b| %>
    <div class="card boat-card w-300 m-1 d-flex rec-bookings">
    <div id="my-boats-booking-card">
      <div class="d-flex test">
        <div class="card-avatar"><%= image_tag b.consumer.user_pic_url, class: "avatar card-avatar"%></div>
        <div class="p-2">Booked by: <%= b.consumer.email %></div>
      </div>

      <div>
        <div class="p-2">Boat name: <%= b.boat.boat_name %></div>
        <div class="p-2">From: <%= b.start_date%> - To: <%= b.end_date %></div>
      </div><p></p>

      <img class="my-boats-booking-img" src="<%= b.boat.photo %>" alt="<%= b.boat.boat_name %>" height="100px">
    </div>


    </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_banner.html.erb
 <div class="banner">
  <div class="container">
    <h1>My bookings:</h1>
    <% if user_signed_in? %>
    <% @my_bookings.order(:start_date).each do |b| %>
    <p><%= b.start_date  %> -- <%= b.end_date %>&nbsp&nbsp: <%= link_to b.boat.boat_name, boat_path(b.boat) %></p>
    <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <!--<%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %> -->
    <%= image_tag "logo_6.png" %>
    <% end %>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <!-- input by OscNil -->
        <li class="nav-item">
          <%= link_to "My bookings", "#", class: "nav-link", id: "my-bookings" %>
        </li>
        <li class="nav-item">
          <%= link_to "Offer boat", new_boat_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          My boats
        </a>
          <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdown">
            <% @my_boats.each do |boat| %>
              <%= link_to boat.boat_name, boat_path(boat), class: "dropdown-item" %>
            <% end %>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to "Received bookings", my_received_bookings_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Find a boat", boats_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag current_user.user_pic_url, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Find a boat", boats_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Offer boat", new_boat_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Log in / Sign up', new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>